### ISSUE TITLE
How to restart a room?

### ISSUE THREAD

**Issue by abathellier** [AgoraIO-Community/CloudClass-Desktop#100]
When the room end we have an error message: `Room is end! (Error 600001-20410100)`. How to reset or remove the room and launch it again?

**Edit**:

Found some doc here: https://docs.agora.io/en/agora-class/faq/agora_class_state

It seems impossible to reset the classroom when it has been ended. You have to wait 1 hour, for the server to delete it.

**Comment by SunGiantor** [comment]
One hour after the end of the room, it will be destroyed. We do not recommend that a room be reused. After the room is finished, create a new room to use

**Comment by ApaasEdu** [comment]
If the room is too short,  you can set the duration of the room at creation time. 
Please refer Parameter “Duration” to https://docs.agora.io/en/agora-class/agora_class_api_ref_web?platform=Web#launchoption

**Comment by abathellier** [comment]
Thank you! Is there a limit for the duration?

**Comment by ApaasEdu** [comment]
Yes，86400 seconds（one day）

**Comment by abathellier** [comment]
Thank you for your answers 🙏
