### ISSUE TITLE
Global css isolation

### ISSUE THREAD

**Issue by abathellier** [AgoraIO-Community/CloudClass-Desktop#102]
Your script add a lot of global css which conflicts with the css of my application... Is there a way to avoid this?

The script is loaded like this:
```html
<script
  id="agora-edu-sdk"
  src="https://download.agora.io/edu-apaas/release/edu_sdk@2.7.1.bundle.js"
/>
```

**Comment by fridaythx** [comment]
In this case, you can embed your classroom page into an iframe which isolates JS Runtime and CSS.
