### ISSUE TITLE
error Command "bootstrap" not found.

### ISSUE THREAD

**Issue by ChenBigFish** [AgoraIO-Community/CloudClass-Desktop#104]
https://docs.agora.io/en/flexible-classroom/get-started/?platform=web

I followed the steps on this page and successfully ran 2.7.1
But 2.8.1 failed and got the error reported, as shown in the picture

![image](https://user-images.githubusercontent.com/99011627/207595092-b00b64f9-9d85-4736-9e1c-d0642d7ba2d3.png)

**Comment by CavanSu** [comment]
We moved App code into new repo:  https://github.com/AgoraIO-Community/flexible-classroom-desktop , 
you can follow this readme: https://github.com/AgoraIO-Community/flexible-classroom-desktop/blob/release/2.8.0/README.md,  and run this app
