### ISSUE TITLE
NextJs App With Agora Flexible Classroom Issue on error - Module not found: Can't resolve '../../build/Release/agora_node_ext'

### ISSUE THREAD

**Issue by pravinmobilefirst9** [AgoraIO-Community/CloudClass-Desktop#105]
Hello Support, 

We are trying to install the Agora classroom SDK on our Next Js Application, We are not getting the direction from where the code is breaking once it starting to build the application.

Here is attached reference screenshot of error message we are facing.
![image](https://user-images.githubusercontent.com/81845996/226974333-70a0dec7-e02a-42de-86e6-3a3987c8ca81.png)

Error is - error - ./node_modules/agora-classroom-sdk/node_modules/agora-electron-sdk/js/Api/index.js:6:0
Module not found: Can't resolve '../../build/Release/agora_node_ext'

Could you please help us or direct us how can we resolve this and take the right direction for installation of the SDK on our codebase.

I have hosted my codebase on Vercel Platform.
https://agoraclassroom.vercel.app/

Thank You so much.

**Comment by plutoless** [comment]
@pravinmobilefirst9 if you are using web only. try removing agora-electron-sdk from package.json dependencies.

**Comment by pravinmobilefirst9** [comment]
Hi, We have tried this but still getting the error with below details,

![image](https://user-images.githubusercontent.com/81845996/227918201-c0a230fd-8194-4dd1-af24-c0c26990ff16.png)


Thanks.

**Comment by SunGiantor** [comment]
Add a line of code to the webpack.base.js file
You can try like this

module.exports = {
// add this code
externals: { 'agora-electron-sdk': 'commonjs2 agora-electron-sdk' },
resolve: {
fallback: {
    crypto: require.resolve('crypto-browserify'),
    stream: require.resolve('stream-browserify'),
    buffer: require.resolve('buffer/'),
},
