### ISSUE TITLE
这个错误是找不到sdk么

### ISSUE THREAD

**Issue by Jastyle** [AgoraIO-Community/CloudClass-Desktop#14]
在编译的时候报了这个错，Module not found: Error: ERROR in ./src/components/app/index.js
Module not found: Error: Can't resolve 'agora-classroom-sdk' in '/Users/jastyle/Desktop/Jastyle/pythonProjects/CloudClass-Desktop/packages/agora-web-edu-demo/src/components/app'   这个问题如何解决

**Comment by plutoless** [comment]
有执行npm install吗？npm install是否有报错

**Comment by Jastyle** [comment]
> 有执行npm install吗？npm install是否有报错

这个问题解决了，在agora-web-edu-demo目录下npm i导致找不到依赖，应该在root目录下执行。
