### ISSUE TITLE
前端如何监听在classroom触发的各种事件

### ISSUE THREAD

**Issue by Jastyle** [AgoraIO-Community/CloudClass-Desktop#15]
比如开始上课、结束上课等事件，有回调的函数么。我只看到了一个事件监听回调
`AgoraEduSDK.launch(
        document.querySelector(`#${this.elem.id}`), {
          rtmToken: "006ab68718dc761451fb9207c2f6406f28cIAB09glttLE9/F4pCdnPT2BZMzFzyA1px7NwZwZkogjIxqFa4MYAAAAAEABay44EKCBTYAEA6AO43FFg",
          userUuid: "ddd9254b136748179adff69aa6892327",
          userName: "teacher",
          roomUuid: "testa689232712",
          roleType: 1,
          roomType: 0,
          roomName: "测试课堂",
          pretest: false,
          language: "zh",
          listener: (evt) => {
            console.log("evt", evt)
          }
        }
      )`
是在listener中监听各种事件，有没有具体的文档，我用的是agro-web-edu-demo 这个demo。

**Comment by plutoless** [comment]
@Jastyle 我们提供了服务端接口拉取对应的事件
https://docs.agora.io/cn/agora-class/agora_class_restful_api?platform=All%20Platforms#%E6%8E%A5%E5%8F%A3%E6%8F%8F%E8%BF%B0-3

**Comment by Jastyle** [comment]
> @Jastyle 我们提供了服务端接口拉取对应的事件
> https://docs.agora.io/cn/agora-class/agora_class_restful_api?platform=All%20Platforms#%E6%8E%A5%E5%8F%A3%E6%8F%8F%E8%BF%B0-3

目前不提供前端回调触发么，后端轮询api还得通知到前端，这样实现就复杂许多。

**Comment by plutoless** [comment]
这边大概需要实现一个怎么样的业务需求?

**Comment by Jastyle** [comment]
一个大概使用场景之一，就是老师结束课程后需要通知老师完成本节课的课堂总结。因为没有做推送通知，所以这个业务逻辑有前端触发。

**Comment by plutoless** [comment]
目前前端有提供
加入教室成功: 1
离开教室成功: 2
两个事件，应该也可以满足您这边的需求的

**Comment by Jastyle** [comment]
> 目前前端有提供
> 加入教室成功: 1
> 离开教室成功: 2
> 两个事件，应该也可以满足您这边的需求的

感谢~ 我看你们有很多开源库，当前这个agro-web-edu-demo使用的sdk 和 这个https://github.com/AgoraIO-Community/eEducation-Web 库 主要什么区别

**Comment by Jastyle** [comment]
我们前端架构是基于vue，如何为模块在vue中引入?

**Comment by plutoless** [comment]
@Jastyle 这个是基于那个做了进一步封装和优化的，后续我们会主要维护这个版本，那个会渐渐停止维护哈

**Comment by plutoless** [comment]
@Jastyle 通过vue准备一个dom，然后在调用launch的时候把dom传入就可以了

**Comment by Jastyle** [comment]
> @Jastyle 通过vue准备一个dom，然后在调用launch的时候把dom传入就可以了



> 目前前端有提供
> 加入教室成功: 1
> 离开教室成功: 2
> 两个事件，应该也可以满足您这边的需求的
下个版本考虑支持前端捕获各种课堂事件么，现在业务场景确实存在很多这样的需求

**Comment by Jastyle** [comment]
> @Jastyle 通过vue准备一个dom，然后在调用launch的时候把dom传入就可以了

我现在如果想传入一个回调函数，触发课堂上各种事件（比如点击下课）能够捕获，或者事件发生时，在launch的listener回调中捕获，如何修改源码实现。

**Comment by plutoless** [comment]
@Jastyle 我们会在下个版本新增一些事件，目前建议还是先通过服务端监听
