### ISSUE TITLE
关于mac屏幕分享问题

### ISSUE THREAD

**Issue by ju4tin** [AgoraIO-Community/CloudClass-Desktop#16]
你好,electron编译的mac端屏幕分享是不是需要授权?
![11](https://user-images.githubusercontent.com/6663073/112111449-29395580-8bef-11eb-9f12-40ab22b8e2bd.png)
目前是黑的,系统授权界面也没有需要授权的选项
![22](https://user-images.githubusercontent.com/6663073/112111709-892ffc00-8bef-11eb-994a-16c15e5f499c.png)
本人是做移动平台开发的,对于electron是菜鸟,不知道是sdk问题,还是需要额外添加屏幕授权的代码,望指教,谢谢!

**Comment by plutoless** [comment]
@ju4tin 你是在开发模式，还是打了release包？

**Comment by ju4tin** [comment]
@plutoless 直接调试运行和打包,貌似选择分享屏幕界面都是如上图黑色一块,需要往entitlements加权限吗？

**Comment by ju4tin** [comment]
貌似需要直接在系统“屏幕录制”中直接添加app才能用，如下图
<img width="668" alt="截屏2021-03-30 下午1 56 08" src="https://user-images.githubusercontent.com/6663073/112940855-52626480-9160-11eb-87cb-d7f5d4f46f9b.png">
请问能往这个界面旁边加app预选项吗？
