### ISSUE TITLE
electron本地运行失败

### ISSUE THREAD

**Issue by york552** [AgoraIO-Community/CloudClass-Desktop#18]
按文档的步骤进行，在运行到npm run dev时报错，麻烦看一下是什么情况呢
npm ERR! code 127
npm ERR! path /Users/yueke/Desktop/毕业设计相关/CloudClass-Desktop/packages/agora-electron-edu-demo
npm ERR! command failed
npm ERR! command sh -c cross-env NODE_OPTIONS=--max-old-space-size=8196 electron-webpack dev

**Comment by plutoless** [comment]
您把完整的信息发出来看下

**Comment by york552** [comment]
npm run dev                                     

> agora-edu-electron-app@1.0.0 dev
> cross-env NODE_OPTIONS=--max-old-space-size=8196 electron-webpack dev

node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: spawn electron-webpack ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn electron-webpack',
  path: 'electron-webpack',
  spawnargs: [ 'dev' ]
}
npm ERR! code 1
npm ERR! path /Users/yueke/Desktop/毕业设计相关/CloudClass-Desktop/packages/agora-electron-edu-demo
npm ERR! command failed
npm ERR! command sh -c cross-env NODE_OPTIONS=--max-old-space-size=8196 electron-webpack dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yueke/.npm/_logs/2021-04-26T08_51_07_423Z-debug.log

**Comment by plutoless** [comment]
感觉是依赖没装好，这边怎么安装的依赖呢

**Comment by york552** [comment]
我就根据文档执行npm install，然后装了cross-env

**Comment by plutoless** [comment]
这个错误的意思是找不到electron-webpack

**Comment by york552** [comment]
弄好了 感谢
