### ISSUE TITLE
示例里的H5课件怎么对接和上传？

### ISSUE THREAD

**Issue by cwg31825** [AgoraIO-Community/CloudClass-Desktop#27]
![image](https://user-images.githubusercontent.com/25262280/123812509-bb57a500-d926-11eb-914d-96090adc6f03.png)

**Comment by cwg31825** [comment]
@plutoless 没找到集成H5课件方面文档

**Comment by Matrixbirds** [comment]
可以描述下您的场景吗？@cwg31825

**Comment by cwg31825** [comment]
![image](https://user-images.githubusercontent.com/25262280/124063218-e5af7c80-da64-11eb-8701-7def0e76d66b.png)
![image](https://user-images.githubusercontent.com/25262280/124063250-feb82d80-da64-11eb-88e8-94693df708d8.png)
@plutoless 就是这个demo里的H5课件是怎么加的https://webdemo.agora.io/flexible-classroom/prod/dev_apaas_1.1.2/20210617_1587/#/

**Comment by cwg31825** [comment]
@plutoless 灵动课堂 aPaaS 解决方案里H5课件怎么使用

**Comment by cwg31825** [comment]
![image](https://user-images.githubusercontent.com/25262280/124218165-448bf900-db2c-11eb-8240-426d0c264d04.png)
我的H5课件是这样的

**Comment by fridaythx** [comment]
当前版本暂不支持此格式H5课件
