### ISSUE TITLE
可以加入房间，但无法显示对方视频画面

### ISSUE THREAD

**Issue by Jastyle** [AgoraIO-Community/CloudClass-Desktop#31]
一对一班级，用的rtmToken 测试，学生和老师都可以进入房间，可以打开视频，但相互看不到对方画面，只能看到自己的画面。我理解房间号其实就是channel吧，进入同一个channel是可以视频通信吧，是因为rtmtoken支持？

**Comment by Jastyle** [comment]
![image](https://user-images.githubusercontent.com/13916468/124888573-cd150880-e008-11eb-86d8-185deb6f8737.png)  大致的参数配置

**Comment by Matrixbirds** [comment]
@Jastyle  您用的是哪个版本的agora-classroom-sdk 能发我一下吗

**Comment by Jastyle** [comment]
> @Jastyle 您用的是哪个版本的agora-classroom-sdk 能发我一下吗

![image](https://user-images.githubusercontent.com/13916468/127461026-2f9501a0-2e07-4d42-b457-7915e073bd47.png)

我看console log 报了订阅对方失败
![image](https://user-images.githubusercontent.com/13916468/127461219-aa035ccd-54b5-4908-a97e-79a762892adc.png)
这是线上https部署后的报错日志

**Comment by Jastyle** [comment]
补充一下，我看SDK里有个serviceWorker.js, 这个是什么作用，貌似这个问题由这个文件导致的
