### ISSUE TITLE
400 Error trying to load https://api.agora.io/cn/edu/apps/.../v2/configs

### ISSUE THREAD

**Issue by davidshq** [AgoraIO-Community/CloudClass-Desktop#33]
I'm trying to run this CloudClass-Desktop sample on my system. I'm running Ubuntu 20.04 and using Visual Studio Code with Remote Containers.

I've spun up a container using VSC that runs Debian 10 (buster) and runs node.js 12.22.3.

I've installed yarn using `npm i -g yarn` and lerna via `yarn global add lerna`. I've then run `yarn bootstrap`. This fails initially due to the Electron code (it's an unsupported system).

I start the application: `yarn run:apaas`. It seems to run but the page is empty.

To be safe I remove the algora-electron-edu-demo folder and it's contents. Then I rerun `yarn bootstrap` followed by `yarn run:apaas` and the same thing happens.

All yarn's logging indicates everything is working fine. Looking at the browser console I'm seeing it:

1. set the config appId, 
2. "launch"
3. GET https://api.agora.io/cn/edu/apps/deletedappId/v2/configs returning a 400 error 
4. Returns the HTTP 400 response
5. Throws "Uncaught (in promise) s: Please setting Netless token in the Console."

Any suggestions on resolving this?

Thanks!

**Comment by Matrixbirds** [comment]
Can u copy the bad request response here, I am support you find the problem.

**Comment by davidshq** [comment]
I spoke with Ryan Burne and he informed me that in addition to the README.md I needed to follow the [documentation found here](https://docs.agora.io/en/agora-class/agora_class_prep).

After following these instructions and rerunning `yarn run:apaas` the error appears slightly different:

1. set config appId,
2. launch app,
3. pass the rtmToken
4. Returns a HTTP 401 response

```
VM1337:1 GET https://api.agora.io/cn/edu/apps/ed05531dc79d4d24b25151cf76426704/v2/configs 401 (Unauthorized)
(anonymous) @ VM1337:1
eval @ edu_sdk.bundle.js:85
u @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
i @ edu_sdk.bundle.js:85
s @ edu_sdk.bundle.js:85
eval @ edu_sdk.bundle.js:85
eval @ edu_sdk.bundle.js:85
eval @ edu_sdk.bundle.js:85
eval @ edu_sdk.bundle.js:57
u @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
o @ edu_sdk.bundle.js:57
s @ edu_sdk.bundle.js:57
eval @ edu_sdk.bundle.js:57
eval @ edu_sdk.bundle.js:57
eval @ edu_sdk.bundle.js:57
eval @ edu_sdk.bundle.js:34
u @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
c @ edu_sdk.bundle.js:34
a @ edu_sdk.bundle.js:34
eval @ edu_sdk.bundle.js:34
eval @ edu_sdk.bundle.js:34
eval @ edu_sdk.bundle.js:34
eval @ edu_sdk.bundle.js:304
u @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
gs @ edu_sdk.bundle.js:304
a @ edu_sdk.bundle.js:304
eval @ edu_sdk.bundle.js:304
a @ edu_sdk.bundle.js:304
r.value @ edu_sdk.bundle.js:304
setupClassroom @ index.js:27
eval @ index.js:10
load (async)
eval @ index.js:7
./src/index.js @ bundle.js:1324
__webpack_require__ @ bundle.js:790
fn @ bundle.js:101
eval @ client:3
1 @ bundle.js:1335
__webpack_require__ @ bundle.js:790
(anonymous) @ bundle.js:857
(anonymous) @ bundle.js:860
Show 9 more frames
edu_sdk.bundle.js:16 15:45:02:987 AgoraEdu-SDK [INFO]:  [http] GET#https://api.agora.io/cn/edu/apps/ed05531dc79d4d24b25151cf76426704/v2/configs response params:  {
"method":"GET",
"headers":
{
"Content-Type":"application/json",
"x-agora-token":"deletedtoken",
"x-agora-uid":"test"}
}  
response:  {
"message":"token is expired",
"__status":401
}  status:  401  statusText:  Unauthorized
edu_sdk.bundle.js:16 Uncaught (in promise) s
tr @ edu_sdk.bundle.js:16
r @ edu_sdk.bundle.js:16
eval @ edu_sdk.bundle.js:16
s @ edu_sdk.bundle.js:16
ar @ edu_sdk.bundle.js:16
eval @ edu_sdk.bundle.js:57
u @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
eval @ edu_sdk.bundle.js:117
o @ edu_sdk.bundle.js:57
s @ edu_sdk.bundle.js:57
Promise.then (async)
gs @ edu_sdk.bundle.js:304
a @ edu_sdk.bundle.js:304
eval @ edu_sdk.bundle.js:304
a @ edu_sdk.bundle.js:304
r.value @ edu_sdk.bundle.js:304
setupClassroom @ index.js:27
eval @ index.js:10
load (async)
eval @ index.js:7
./src/index.js @ bundle.js:1324
__webpack_require__ @ bundle.js:790
fn @ bundle.js:101
eval @ client:3
1 @ bundle.js:1335
__webpack_require__ @ bundle.js:790
(anonymous) @ bundle.js:857
(anonymous) @ bundle.js:860
```

The token I was using was the NETLESS token - is that incorrect?

**Comment by davidshq** [comment]
Figured it out. For some reason the temp token I created a little while ago wasn't valid, so I swapped in a new temp token and that one worked.
