### ISSUE TITLE
依赖项错误: white-web-sdk

### ISSUE THREAD

**Issue by zongyi** [AgoraIO-Community/CloudClass-Desktop#64]
使用yarn安装的依赖：

`"agora-classroom-sdk": "^1.1.5-rc.2",`

需要展示课件视频，运行时显示：

```
index.js:1 Error: @netless/video-js-plugin@0.3.8 requires white-web-sdk@^2.13.8 to work properly.
```

课件中图片可以展示，但是音频/视频不行。

谢谢

**Comment by Matrixbirds** [comment]
@zongyi 请问你是用哪个分支复现的？

**Comment by zongyi** [comment]
> @zongyi 请问你是用哪个分支复现的？

我是直接从npm源导入的，并没有自己修改。
导入的版本为：1.1.5-rc.2

后经过测试，直接使用 https://docs.agora.io/cn/agora-class/agora_class_quickstart_web?platform=Web 中提到的，将外链js的版本改成1.1.5也不行。使用网盘功能时，也会报同样的错误。

谢谢

**Comment by Matrixbirds** [comment]
@zongyi  这个问题我已经修复了，您这边再更新一下master分支的最新代码。
