### ISSUE TITLE
Win10LTSC-1809 中 执行 yran run:pass 后报错 'NODE_ENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by yooyui** [AgoraIO-Community/CloudClass-Desktop#68]
```
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
lerna ERR! npm run dev exited 2 in 'agora-apaas-demo'
lerna ERR! npm run dev exited 2 in 'agora-apaas-demo'
error Command failed with exit code 2.
```

**Comment by Matrixbirds** [comment]
您这边执行的是哪个分支的代码？

**Comment by moly52** [comment]
> ```
> 'NODE_ENV' is not recognized as an internal or external command,
> operable program or batch file.
> lerna ERR! npm run dev exited 2 in 'agora-apaas-demo'
> lerna ERR! npm run dev exited 2 in 'agora-apaas-demo'
> error Command failed with exit code 2.
> ```

我这边是Windows环境，修改 packages\agora-apaas-demo\package.json
    "dev": "webpack-cli && NODE_ENV=development webpack serve",
添加 set 
    "dev": "webpack-cli && set NODE_ENV=development webpack serve",
然后过了这一步。

现在没报错了，但是我这里 http://localhost:9000/ 访问后没反应。。。


![image](https://user-images.githubusercontent.com/19373946/143405226-0d4c6281-232a-4f1f-969c-0413ecf15181.png)

**Comment by moly52** [comment]
ok 能运行了。
packages\agora-apaas-demo\public\index.html ，
packages\agora-apaas-demo\public\bundle\bundle.js ，
注意 index.html  的路径 <script src="bundle.js"></script>

然后把  index.html 及 bundle.js 放到 tomcat 下，能访问到了

或者是直接按照这个文档来
https://docs.agora.io/cn/agora-class/agora_class_quickstart_web?platform=Web#%E5%90%AF%E5%8A%A8%E7%81%B5%E5%8A%A8%E8%AF%BE%E5%A0%82

**Comment by yooyui** [comment]
> 

谢谢

**Comment by yooyui** [comment]
已经解决了。
