### ISSUE TITLE
Agora Flexible classroom - Chat not working

### ISSUE THREAD

**Issue by mamun724682** [AgoraIO-Community/CloudClass-Desktop#71]
I just launched agora flexible classroom. But the chat module is not working and it's showing this console error. How do I solve this issue and chat work? Here are my codes. Please check:

SDK: https://download.agora.io/edu-apaas/release/edu_sdk_1.1.5.10.js

AgoraEduSDK.config({
                // Here pass in the Agora App ID you have got
                appId: self.agora_id,
            })
            AgoraEduSDK.launch(
                document.querySelector("#classroom"), {
                    // Here pass in the RTM token you have generated
                    rtmToken: self.token,
                    // The user ID must be the same as the one you used for generating the RTM token
                    userUuid: self.authuserid,
                    userName: self.authuser,
                    roomUuid: "6441444714144", //Should be unique and generate when join
                    roomName: "demo-class", //Any
                    roleType: 1, //teacher = 1, student = 2, assistant = 3
                    roomType: 4, // Room1v1Class = 0, RoomBigClass = 2, RoomSmallClass = 4
                    pretest: true,
                    language: "en",
                    startTime: new Date().getTime(),
                    duration: 60 * 30, // dynamic time
                    courseWareList: [],
                    listener: (evt) => {
                        if (evt == 1){
                            this.joined = true //Ready
                        }
                        if (evt == 2){
                            this.joined = false //Leave
                        }
                        console.log("evt", evt)
                    }
                }
            )

![image](https://user-images.githubusercontent.com/41566116/150090056-49ff9568-e758-46da-b987-7e9c6b690eb7.png)

**Comment by mohamed-mashaly1403** [comment]
have you manged to fix this?

**Comment by MR-AMDEV** [comment]
Exactly still not working. Please anybody help

**Comment by fridaythx** [comment]
version 1.x is no longer being developed and maintained, please have a try on 2.x version.
