### ISSUE TITLE
进入房间失败，响应400：{"message":"appid is invalid"}

### ISSUE THREAD

**Issue by simonwzb** [AgoraIO-Community/CloudClass-Desktop#79]
我确认我的appid是跟agora管理系统-项目配置里的一模一样的
但是为何这里返回400？响应信息是appid不对呢？

用的分支：release1.0.1
修改的都是依赖的版本，没有动代码
在.env和.env.dev里加了REACT_APP_NETLESS_APP_ID，否则运行报错

@plutoless @Matrixbirds @fridaythx @saino @QinZhen001 
汗。。。

![image](https://user-images.githubusercontent.com/8718470/157641382-06d7f78d-1c24-45ec-8b42-f766ec1f1d59.png)
![image](https://user-images.githubusercontent.com/8718470/157641676-cb8b2d0c-d6bf-4e2c-a485-872dc54e6280.png)

**Comment by simonwzb** [comment]
项目状态是已上线（非测试版），配置了阿里云oss，没有配置环信

**Comment by fridaythx** [comment]
请问使用的哪个分支？这个错误应该是因为使用了错误的AppId，请检查下.env.dev和.env文件中配置
REACT_APP_AGORA_APP_ID，REACT_APP_AGORA_APP_CERTIFICATE已经正确填写
