### ISSUE TITLE
The link to plugin gallery in website is wrong

### ISSUE THREAD

**Issue by ahkhanjani** [AgoraIO-Community/CloudClass-Desktop#85]
In [this part of the guide](https://docs.agora.io/en/agora-class/agora_class_ext_app_web?platform=Web#1-implement-a-plugin) clicking on the link to the plugin gallery ends up in 404 error. The link must probably be updated to [this](https://github.com/AgoraIO-Community/CloudClass-Desktop/tree/release/apaas/2.4.1/packages/agora-plugin-gallery).

**Comment by fridaythx** [comment]
Thanks for the correction, we will update this link soon.
