### ISSUE TITLE
demo跑不起来

### ISSUE THREAD

**Issue by babysbreath1994** [AgoraIO-Community/CloudClass-Desktop#86]
2.4.1跑就报错了

**Comment by babysbreath1994** [comment]
cross-env NODE_OPTIONS=--max_old_space_size=8192 webpack serve --config ./webpack/webpack.dev.js
[webpack-cli] Failed to load 'C:\Users\wanqian\CloudClass-Desktop\packages\agora-classroom-sdk\webpack\webpack.dev.js' config
[webpack-cli] Error: Cannot find module 'agora-edu-core/package.json'
Require stack:

**Comment by Gxscccc** [comment]
我也遇到了这样的问题，请问你决解了吗？

**Comment by SunGiantor** [comment]
删除空的agora-edu-core文件夹和空的agora-rte-sdk文件夹就可以解决这个问题了
