### ISSUE TITLE
怎么加日语翻译

### ISSUE THREAD

**Issue by inoue0124** [AgoraIO-Community/CloudClass-Desktop#87]
你好，我想把UI上的句子给翻译成日语，请问该修改什么文件？

**Comment by SunGiantor** [comment]
如何增加多语言？

以日语为例

1)、主SDK中的多语言文件资源增加到这个目录下：
packages/agora-scenario-ui-kit/src/utilities/translate
在这个目录下增加您的语言文件
例如jpn.ts
在packages/agora-scenario-ui-kit/src/components/i18n/index.tsx目录下i18nResources中增加上面添加的日语类型
在调用AgoraEduSDK.launch接口时候launchOption.language传入自己添加的语言

2）在答题器、定时器、投票器、环信IM中添加自己的语言如下：
在对应的组件目录下
packages/agora-plugin-gallery/src/gallery/counter/i18n 添加自己的语言
例如：i18n.addResourceBundle('zh', 'translation', zh);

**Comment by inoue0124** [comment]
@SunGiantor 
Thank you!
