### ISSUE TITLE
怎么解

### ISSUE THREAD

**Issue by Gxscccc** [AgoraIO-Community/CloudClass-Desktop#88]
[webpack-cli] Failed to load 'C:\Users\dell\Desktop\yuyin\CloudClass-Desktop-dev-apaas-kaikeba\packages\agora-classroom-sdk\webpack\webpack.dev.js' config
[webpack-cli] Error: Cannot find module 'agora-edu-core/package.json'

**Comment by SunGiantor** [comment]
删除agora-edu-core和agora-rte-sdk两个空文件 然后再重新编译
