### ISSUE TITLE
能不能设置聊天用户的头像

### ISSUE THREAD

**Issue by wbkearly** [AgoraIO-Community/CloudClass-Desktop#91]
能不能修改聊天用户的头像 直接使用sdk都是默认的头像

**Comment by SunGiantor** [comment]
可以的，可以在后端调用设置房间属性接口https://docs.agora.io/cn/agora-class/agora_class_restful_api?platform=Web#%E6%9B%B4%E6%96%B0%E8%AF%BE%E5%A0%82%E5%B1%9E%E6%80%A7
将用户列表(包括头像和昵称等）信息传入教室中。
然后在web端在IM模块通过获取列表中自己的头像信息，修改默认头像
将  set(
    uiStore,
    'props.imAvatarUrl',
    'https://download-sdk.oss-cn-beijing.aliyuncs.com/downloads/IMDemo/avatar/Image1.png',
  );

修改为
  var currrentUser = uiStore.classroomStore.roomStore.flexProps.find( (itm: any) => itm.userId == widgetStore.classroomConfig.sessionInfo)
  var userAvatarUrl = currrentUser.avatarUrl

  set(
    uiStore,
    'props.imAvatarUrl',
    userAvatarUrl,
  );

此时发送消息后就会将自己的头像信息同步给远端用户，就可以展示自己的头像了。

**Comment by wbkearly** [comment]
感谢回复！
