### ISSUE TITLE
Chat, whiteboard not working

### ISSUE THREAD

**Issue by webtamizhan** [AgoraIO-Community/CloudClass-Desktop#92]
We tried with the testing appID, appSecret to run the project locally. But the chat & whiteboard not working as expected.

When hit a enter at chat window.

`Uncaught TypeError: Cannot read properties of undefined (reading 'getUniqueId')` exception appered.

**Comment by SunGiantor** [comment]
不配置appId和appSecret的时候，会用我们默认的appId登录，不需配置什么就可以使用。如果您配置了测试appId和appSecret需要在我们agora的console后台配置白板和环信相关的配置才能使用。请参照这个配置文档https://docs.agora.io/cn/agora-class/agora_class_configure?platform=Web#%E9%85%8D%E7%BD%AE%E7%99%BD%E6%9D%BF%E5%8A%9F%E8%83%BD

**Comment by abathellier** [comment]
My whiteboard isn't working either. When I click on the dashboard, I get `AgoraEdu-SDK[3]: [o] The [netlessBoard] widget is already active` in the console but nothing on the screen... Should I provide another sdk key?

**Comment by webtamizhan** [comment]
If anyone facing this issue, please check your aws s3 configuration and your updated configuration in agora, this is why chat and whiteboard was not working for me.
