### ISSUE TITLE
agora-rc-extension error

### ISSUE THREAD

**Issue by Angelxiaotao** [AgoraIO-Community/CloudClass-Desktop#94]
测试环境1：vite2.x + vue3 + typescript
externals已经配置 'agora-electron-sdk': 'commonjs2 agora-electron-sdk'
Could not resolve "../build/Release/agora-rc-extension" 错误加载失败。

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/37688951/178129569-16b59b2e-26a4-4e3f-9caa-7df417e7cc5c.png">

**Comment by SunGiantor** [comment]
externals: {
    'agora-electron-sdk': 'commonjs2 agora-electron-sdk',
    'agora-rdc-core': 'commonjs2 agora-rdc-core',
  },

**Comment by Angelxiaotao** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/37688951/178275389-67e70a9d-14ce-43d6-b8d2-db3d5c28fc19.png">
请问出现这个错误是为啥。   能正常直播。我在咱们官网提交的工单CSP-22202。里面demo也会出现这个错误
