### ISSUE TITLE
因为npm源导致 yarn pack:electron:win 执行失败

### ISSUE THREAD

**Issue by wisecsj** [AgoraIO-Community/CloudClass-Desktop#97]
.npmrc配置的是走阿里的源。但是在打包下载electron的时候报错
![image](https://user-images.githubusercontent.com/10665384/184131974-50ed65e3-6912-4d8c-a230-d31c6917d3b1.png)
发现是红圈处最前面少了v导致。但我不知道怎么fix这个问题，不熟前端工具

目前我是注释掉了，去走腾讯源是ok的

**Comment by fridaythx** [comment]
可以在.npmrc文件中electron_mirror这行下增加一行：electron-custom-dir=v12.0.0
即可解决此问题，新版本中会修复.npmrc文件。
