### ISSUE TITLE
demo创建房间登入请求的时候404，在哪改

### ISSUE THREAD

**Issue by Janix520** [AgoraIO-Community/CloudClass-Desktop#99]
登入的时候请求地址域名后面貌似是区域获取到的是 /Undefined，但是看了很久也不太清楚哪里改

**Comment by fridaythx** [comment]
看起来像环境变量未注入导致的API前缀不正确。
请参考readme.md文件中的指引，拷贝.env文件到packages/agora-classroom-sdk目录下。
